//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Admin_Prac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cleaner
    {
        public int Id { get; set; }
        public string CleanerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public string Password { get; set; }
        public bool AdminApproved { get; set; }
        public string ContactNumber { get; set; }
    }
}
