//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_Admin_Prac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public string cardNumber { get; set; }
        public Nullable<int> ExpMonth { get; set; }
        public Nullable<int> ExpYear { get; set; }
        public Nullable<int> cvv { get; set; }
        public string name { get; set; }
        public Nullable<double> amount { get; set; }
        public string Method { get; set; }
    }
}
